--liquibase formatted sql

--changeset ninggiangboy:001-01-create-identity-tables
CREATE TABLE iam_accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    email       VARCHAR(255),
    phone_number VARCHAR(50),
    password_hash VARCHAR(255),
    status      VARCHAR(50)  NOT NULL,
    email_verified BOOLEAN   NOT NULL DEFAULT FALSE,
    phone_verified BOOLEAN   NOT NULL DEFAULT FALSE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    last_login_ip VARCHAR(45),
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ
);

CREATE INDEX idx_iam_accounts_status ON iam_accounts (status);
CREATE INDEX idx_iam_accounts_deleted_at ON iam_accounts (deleted_at);
CREATE TABLE iam_account_credentials (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                VARCHAR(36)  NOT NULL,
    account_id          BIGINT       NOT NULL,
    provider            VARCHAR(50)  NOT NULL,
    provider_account_id VARCHAR(255) NOT NULL,
    access_token        TEXT,
    refresh_token       TEXT,
    created_by          BIGINT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by          BIGINT,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMPTZ
);

CREATE INDEX idx_iam_account_credentials_account_id ON iam_account_credentials (account_id);
CREATE INDEX idx_iam_account_credentials_deleted_at ON iam_account_credentials (deleted_at);
CREATE TABLE iam_account_devices (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           VARCHAR(36)  NOT NULL,
    account_id     BIGINT       NOT NULL,
    device_type    VARCHAR(50)  NOT NULL,
    device_name    VARCHAR(255),
    fingerprint    VARCHAR(255),
    user_agent     TEXT,
    push_token     VARCHAR(255),
    last_active_at TIMESTAMPTZ,
    is_trusted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by     BIGINT,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at     TIMESTAMPTZ
);

CREATE INDEX idx_iam_account_devices_account_id ON iam_account_devices (account_id);
CREATE INDEX idx_iam_account_devices_fingerprint ON iam_account_devices (fingerprint);
CREATE INDEX idx_iam_account_devices_deleted_at ON iam_account_devices (deleted_at);
CREATE TABLE iam_account_sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    account_id  BIGINT       NOT NULL,
    device_id   BIGINT,
    token_hash  VARCHAR(255) NOT NULL,
    ip_address  VARCHAR(45),
    expires_at  TIMESTAMPTZ  NOT NULL,
    is_revoked  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_iam_account_sessions_account_id ON iam_account_sessions (account_id);
CREATE INDEX idx_iam_account_sessions_token_hash ON iam_account_sessions (token_hash);
CREATE TABLE iam_account_otps (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    account_id BIGINT       NOT NULL,
    code       VARCHAR(20)  NOT NULL,
    purpose    VARCHAR(50)  NOT NULL,
    channel    VARCHAR(50)  NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    is_used    BOOLEAN      NOT NULL DEFAULT FALSE,
    attempts   INTEGER      NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_iam_account_otps_account_id ON iam_account_otps (account_id);
CREATE INDEX idx_iam_account_otps_purpose_channel ON iam_account_otps (account_id, purpose, channel);
CREATE TABLE iam_account_login_histories (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           VARCHAR(36) NOT NULL,
    account_id     BIGINT      NOT NULL,
    device_id      BIGINT,
    ip_address     VARCHAR(45),
    user_agent     TEXT,
    result         VARCHAR(50) NOT NULL,
    failure_reason TEXT,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by     BIGINT,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_iam_account_login_histories_account_id ON iam_account_login_histories (account_id);
CREATE INDEX idx_iam_account_login_histories_created_at ON iam_account_login_histories (created_at);
--rollback DROP TABLE iam_account_login_histories; DROP TABLE iam_account_otps; DROP TABLE iam_account_sessions; DROP TABLE iam_account_devices; DROP TABLE iam_account_credentials; DROP TABLE iam_accounts;
