--liquibase formatted sql

--changeset ninggiangboy:002-01-create-profile-tables
CREATE TABLE prf_profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         VARCHAR(36)  NOT NULL,
    account_id   BIGINT       NOT NULL,
    username     VARCHAR(50)  NOT NULL,
    display_name VARCHAR(100),
    bio          TEXT,
    website      VARCHAR(500),
    location     VARCHAR(255),
    avatar_url   VARCHAR(500),
    banner_url   VARCHAR(500),
    visibility   VARCHAR(50)  NOT NULL DEFAULT 'PUBLIC',
    is_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_celeb     BOOLEAN      NOT NULL DEFAULT FALSE,
    public_key   TEXT,
    version      BIGINT       NOT NULL DEFAULT 0,
    created_by   BIGINT,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by   BIGINT,
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ
);

COMMENT ON COLUMN prf_profiles.public_key IS
    'Base64-encoded ECDH public key (X25519). Used for E2E encrypted message key exchange.';

CREATE UNIQUE INDEX uq_prf_profiles_username ON prf_profiles (username);
CREATE UNIQUE INDEX uq_prf_profiles_account_id ON prf_profiles (account_id);
CREATE INDEX idx_prf_profiles_visibility ON prf_profiles (visibility);
CREATE INDEX idx_prf_profiles_deleted_at ON prf_profiles (deleted_at);
CREATE INDEX idx_prf_profiles_is_celeb ON prf_profiles (is_celeb) WHERE is_celeb = TRUE;

CREATE TABLE prf_profile_stats (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL,
    profile_id      BIGINT      NOT NULL,
    follower_count  BIGINT      NOT NULL DEFAULT 0,
    following_count BIGINT      NOT NULL DEFAULT 0,
    thread_count    BIGINT      NOT NULL DEFAULT 0,
    like_count      BIGINT      NOT NULL DEFAULT 0,
    media_count     BIGINT      NOT NULL DEFAULT 0,
    version         BIGINT      NOT NULL DEFAULT 0,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      BIGINT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE prf_profile_settings (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    profile_id           BIGINT      NOT NULL,
    allow_mentions       BOOLEAN     NOT NULL DEFAULT TRUE,
    allow_messages       BOOLEAN     NOT NULL DEFAULT TRUE,
    allow_tagging        BOOLEAN     NOT NULL DEFAULT TRUE,
    show_activity_status BOOLEAN     NOT NULL DEFAULT TRUE,
    version              BIGINT      NOT NULL DEFAULT 0,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE prf_profile_activities (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL,
    profile_id      BIGINT      NOT NULL,
    last_active_at  TIMESTAMPTZ,
    last_post_at    TIMESTAMPTZ,
    version         BIGINT      NOT NULL DEFAULT 0,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      BIGINT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE prf_profile_links (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    profile_id  BIGINT       NOT NULL,
    type        VARCHAR(50)  NOT NULL,
    url         VARCHAR(500) NOT NULL,
    order_index INTEGER      NOT NULL DEFAULT 0,
    version     BIGINT       NOT NULL DEFAULT 0,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_prf_profile_links_profile_id ON prf_profile_links (profile_id);

CREATE TABLE prf_profile_medias (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    profile_id BIGINT       NOT NULL,
    type       VARCHAR(50)  NOT NULL,
    url        VARCHAR(500) NOT NULL,
    metadata   TEXT,
    version    BIGINT       NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_prf_profile_medias_profile_id ON prf_profile_medias (profile_id);

CREATE TABLE prf_profile_metadata (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    profile_id BIGINT       NOT NULL,
    key        VARCHAR(255) NOT NULL,
    value      TEXT,
    version    BIGINT       NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_prf_profile_metadata_profile_id ON prf_profile_metadata (profile_id);

CREATE TABLE prf_profile_usernames (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    profile_id BIGINT      NOT NULL,
    username   VARCHAR(50) NOT NULL,
    is_current BOOLEAN     NOT NULL DEFAULT FALSE,
    version    BIGINT      NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_prf_profile_usernames_profile_id ON prf_profile_usernames (profile_id);
CREATE INDEX idx_prf_profile_usernames_username ON prf_profile_usernames (username);

CREATE TABLE prf_profile_follows (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    follower_profile_id  BIGINT      NOT NULL,
    following_profile_id BIGINT      NOT NULL,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_prf_profile_follows_follower ON prf_profile_follows (follower_profile_id);
CREATE INDEX idx_prf_profile_follows_following ON prf_profile_follows (following_profile_id);

CREATE TABLE prf_profile_blocks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               VARCHAR(36) NOT NULL,
    blocker_profile_id BIGINT      NOT NULL,
    blocked_profile_id BIGINT      NOT NULL,
    created_by         BIGINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by         BIGINT,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_prf_profile_blocks_blocker ON prf_profile_blocks (blocker_profile_id);
CREATE INDEX idx_prf_profile_blocks_blocked ON prf_profile_blocks (blocked_profile_id);

CREATE TABLE prf_profile_mutes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36) NOT NULL,
    muter_profile_id BIGINT      NOT NULL,
    muted_profile_id BIGINT      NOT NULL,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by       BIGINT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_prf_profile_mutes_muter ON prf_profile_mutes (muter_profile_id);
CREATE INDEX idx_prf_profile_mutes_muted ON prf_profile_mutes (muted_profile_id);

CREATE TABLE prf_profile_follow_hashtags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    profile_id BIGINT      NOT NULL,
    hashtag_id BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_prf_profile_follow_hashtags_profile_id ON prf_profile_follow_hashtags (profile_id);
CREATE INDEX idx_prf_profile_follow_hashtags_hashtag_id ON prf_profile_follow_hashtags (hashtag_id);

CREATE TABLE prf_follow_requests (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    requester_profile_id BIGINT      NOT NULL,
    target_profile_id    BIGINT      NOT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    responded_at         TIMESTAMPTZ,
    version              BIGINT      NOT NULL DEFAULT 0,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE prf_follow_requests IS
    'Pending follow requests created when a user attempts to follow a PRIVATE profile.';
COMMENT ON COLUMN prf_follow_requests.status IS
    'Lifecycle: PENDING, APPROVED, REJECTED, CANCELLED.';

CREATE UNIQUE INDEX uq_prf_follow_requests_pending_pair
    ON prf_follow_requests (requester_profile_id, target_profile_id)
    WHERE status = 'PENDING';
CREATE INDEX idx_prf_follow_requests_target_status
    ON prf_follow_requests (target_profile_id, status);
CREATE INDEX idx_prf_follow_requests_requester_status
    ON prf_follow_requests (requester_profile_id, status);

CREATE TABLE prf_profile_stats_delta_processed (
    event_uuid   VARCHAR(36) PRIMARY KEY,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
--rollback DROP TABLE IF EXISTS prf_profile_stats_delta_processed; DROP TABLE IF EXISTS prf_follow_requests; DROP TABLE IF EXISTS prf_profile_follow_hashtags; DROP TABLE IF EXISTS prf_profile_mutes; DROP TABLE IF EXISTS prf_profile_blocks; DROP TABLE IF EXISTS prf_profile_follows; DROP TABLE IF EXISTS prf_profile_usernames; DROP TABLE IF EXISTS prf_profile_metadata; DROP TABLE IF EXISTS prf_profile_medias; DROP TABLE IF EXISTS prf_profile_links; DROP TABLE IF EXISTS prf_profile_activities; DROP TABLE IF EXISTS prf_profile_settings; DROP TABLE IF EXISTS prf_profile_stats; DROP TABLE IF EXISTS prf_profiles;
