--liquibase formatted sql

--changeset ninggiangboy:002-01-create-hashtag-tables
CREATE TABLE ht_hashtags (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           VARCHAR(36)  NOT NULL,
    tag            VARCHAR(255) NOT NULL,
    normalized_tag VARCHAR(255) NOT NULL,
    usage_count    BIGINT       NOT NULL DEFAULT 0,
    thread_count   BIGINT       NOT NULL DEFAULT 0,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by     BIGINT,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at     TIMESTAMPTZ
);
CREATE INDEX idx_ht_hashtags_deleted_at ON ht_hashtags (deleted_at);
CREATE TABLE ht_hashtag_stats (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         VARCHAR(36) NOT NULL,
    hashtag_id   BIGINT      NOT NULL,
    thread_count BIGINT      NOT NULL DEFAULT 0,
    usage_count  BIGINT      NOT NULL DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    created_by   BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by   BIGINT,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE ht_hashtag_metadata (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    hashtag_id  BIGINT       NOT NULL,
    category    VARCHAR(100),
    language    VARCHAR(10),
    description TEXT,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE TABLE ht_hashtag_moderations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    hashtag_id BIGINT      NOT NULL,
    status     VARCHAR(50) NOT NULL,
    reason     TEXT,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE ht_hashtag_relations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                VARCHAR(36) NOT NULL,
    hashtag_a_id        BIGINT      NOT NULL,
    hashtag_b_id        BIGINT      NOT NULL,
    co_occurrence_count BIGINT      NOT NULL DEFAULT 0,
    created_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          BIGINT,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ht_hashtag_relations_hashtag_a_id ON ht_hashtag_relations (hashtag_a_id);
CREATE INDEX idx_ht_hashtag_relations_hashtag_b_id ON ht_hashtag_relations (hashtag_b_id);
CREATE TABLE ht_hashtag_usage_hourly (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36) NOT NULL,
    hashtag_id  BIGINT      NOT NULL,
    hour_bucket TIMESTAMPTZ NOT NULL,
    count       BIGINT      NOT NULL DEFAULT 0,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ht_hashtag_usage_hourly_hashtag_id ON ht_hashtag_usage_hourly (hashtag_id);
CREATE INDEX idx_ht_hashtag_usage_hourly_hour_bucket ON ht_hashtag_usage_hourly (hour_bucket);
--rollback DROP TABLE ht_hashtag_usage_hourly; DROP TABLE ht_hashtag_relations; DROP TABLE ht_hashtag_moderations; DROP TABLE ht_hashtag_metadata; DROP TABLE ht_hashtag_stats; DROP TABLE ht_hashtags;
