--liquibase formatted sql

--changeset ninggiangboy:003-01-create-thread-tables
CREATE TABLE thr_threads (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    author_profile_id    BIGINT      NOT NULL,
    raw_content          TEXT,
    parent_thread_id     BIGINT,
    root_thread_id       BIGINT,
    quote_thread_id      BIGINT,
    like_count           BIGINT      NOT NULL DEFAULT 0,
    reply_count          BIGINT      NOT NULL DEFAULT 0,
    repost_count         BIGINT      NOT NULL DEFAULT 0,
    quote_count          BIGINT      NOT NULL DEFAULT 0,
    bookmark_count       BIGINT      NOT NULL DEFAULT 0,
    view_count           BIGINT      NOT NULL DEFAULT 0,
    status               VARCHAR(50) NOT NULL,
    visibility           VARCHAR(50) NOT NULL,
    reply_restriction    VARCHAR(50),
    is_hide_like_count   BOOLEAN     NOT NULL DEFAULT FALSE,
    is_edited            BOOLEAN     NOT NULL DEFAULT FALSE,
    edited_at            TIMESTAMPTZ,
    scheduled_publish_at TIMESTAMPTZ,
    has_mentions         BOOLEAN     NOT NULL DEFAULT FALSE,
    has_hashtags         BOOLEAN     NOT NULL DEFAULT FALSE,
    has_medias           BOOLEAN     NOT NULL DEFAULT FALSE,
    has_polls            BOOLEAN     NOT NULL DEFAULT FALSE,
    version              BIGINT      NOT NULL DEFAULT 0,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at           TIMESTAMPTZ
);

CREATE INDEX idx_thr_threads_author_profile_id ON thr_threads (author_profile_id);
CREATE INDEX idx_thr_threads_parent_thread_id ON thr_threads (parent_thread_id);
CREATE INDEX idx_thr_threads_root_thread_id ON thr_threads (root_thread_id);
CREATE INDEX idx_thr_threads_status ON thr_threads (status);
CREATE INDEX idx_thr_threads_created_at ON thr_threads (created_at);
CREATE INDEX idx_thr_threads_deleted_at ON thr_threads (deleted_at);

CREATE TABLE thr_thread_medias (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          VARCHAR(36)  NOT NULL,
    thread_id     BIGINT       NOT NULL,
    type          VARCHAR(50)  NOT NULL,
    url           VARCHAR(500) NOT NULL,
    thumbnail_url VARCHAR(500),
    width         INTEGER,
    height        INTEGER,
    duration      INTEGER,
    alt_text      TEXT,
    position      INTEGER      NOT NULL DEFAULT 0,
    created_by    BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by    BIGINT,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_thr_thread_medias_thread_id ON thr_thread_medias (thread_id);

CREATE TABLE thr_thread_mentions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    thread_id            BIGINT      NOT NULL,
    mentioned_profile_id BIGINT      NOT NULL,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_thr_thread_mentions_thread_id ON thr_thread_mentions (thread_id);
CREATE INDEX idx_thr_thread_mentions_mentioned ON thr_thread_mentions (mentioned_profile_id);

CREATE TABLE thr_thread_hashtags (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           VARCHAR(36) NOT NULL,
    thread_id      BIGINT      NOT NULL,
    hashtag_id     BIGINT      NOT NULL,
    position_start INTEGER,
    position_end   INTEGER,
    created_by     BIGINT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by     BIGINT,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_thr_thread_hashtags_thread_id ON thr_thread_hashtags (thread_id);
CREATE INDEX idx_thr_thread_hashtags_hashtag_id ON thr_thread_hashtags (hashtag_id);

CREATE TABLE thr_thread_polls (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    thread_id            BIGINT      NOT NULL,
    expires_at           TIMESTAMPTZ NOT NULL,
    allow_multiple_votes BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE thr_thread_poll_options (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36)  NOT NULL,
    thread_id  BIGINT       NOT NULL,
    option     VARCHAR(255) NOT NULL,
    position   INTEGER      NOT NULL DEFAULT 0,
    vote_count BIGINT       NOT NULL DEFAULT 0,
    version    BIGINT       NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_thr_thread_poll_options_thread_id ON thr_thread_poll_options (thread_id);

CREATE TABLE thr_thread_poll_votes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    thread_id  BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    option_id  BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_thr_thread_poll_votes_thread_id ON thr_thread_poll_votes (thread_id);
CREATE INDEX idx_thr_thread_poll_votes_profile_id ON thr_thread_poll_votes (profile_id);

CREATE TABLE thr_thread_link_previews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    thread_id   BIGINT       NOT NULL,
    url         VARCHAR(500) NOT NULL,
    title       VARCHAR(500),
    description TEXT,
    image_url   VARCHAR(500),
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE thr_thread_likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    thread_id  BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_thr_thread_likes_thread_id ON thr_thread_likes (thread_id);
CREATE INDEX idx_thr_thread_likes_profile_id ON thr_thread_likes (profile_id);

CREATE TABLE thr_thread_reposts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    thread_id  BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_thr_thread_reposts_thread_id ON thr_thread_reposts (thread_id);
CREATE INDEX idx_thr_thread_reposts_profile_id ON thr_thread_reposts (profile_id);

CREATE TABLE thr_thread_bookmarks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    thread_id  BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_thr_thread_bookmarks_thread_id ON thr_thread_bookmarks (thread_id);
CREATE INDEX idx_thr_thread_bookmarks_profile_id ON thr_thread_bookmarks (profile_id);

CREATE TABLE thr_thread_moderations (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    thread_id            BIGINT      NOT NULL,
    reporter_profile_id  BIGINT      NOT NULL,
    reason               TEXT,
    status               VARCHAR(50) NOT NULL,
    moderator_profile_id BIGINT,
    resolution           TEXT,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_thr_thread_moderations_thread_id ON thr_thread_moderations (thread_id);
CREATE INDEX idx_thr_thread_moderations_status ON thr_thread_moderations (status);
--rollback DROP TABLE IF EXISTS thr_thread_moderations; DROP TABLE IF EXISTS thr_thread_bookmarks; DROP TABLE IF EXISTS thr_thread_reposts; DROP TABLE IF EXISTS thr_thread_likes; DROP TABLE IF EXISTS thr_thread_link_previews; DROP TABLE IF EXISTS thr_thread_poll_votes; DROP TABLE IF EXISTS thr_thread_poll_options; DROP TABLE IF EXISTS thr_thread_polls; DROP TABLE IF EXISTS thr_thread_hashtags; DROP TABLE IF EXISTS thr_thread_mentions; DROP TABLE IF EXISTS thr_thread_medias; DROP TABLE IF EXISTS thr_threads;
