--liquibase formatted sql

--changeset ninggiangboy:004-01-create-chat-tables
CREATE TABLE chat_conversations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  VARCHAR(36) NOT NULL,
    type                  VARCHAR(50) NOT NULL,
    created_by_profile_id BIGINT      NOT NULL,
    last_message_id       BIGINT,
    last_message_at       TIMESTAMPTZ,
    version               BIGINT      NOT NULL DEFAULT 0,
    created_by            BIGINT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by            BIGINT,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at            TIMESTAMPTZ
);

CREATE INDEX idx_chat_conversations_creator ON chat_conversations (created_by_profile_id);
CREATE INDEX idx_chat_conversations_last_message_at ON chat_conversations (last_message_at);
CREATE INDEX idx_chat_conversations_deleted_at ON chat_conversations (deleted_at);

CREATE TABLE chat_conversation_participants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL,
    conversation_id BIGINT      NOT NULL,
    profile_id      BIGINT      NOT NULL,
    role            VARCHAR(50) NOT NULL,
    joined_at       TIMESTAMPTZ,
    left_at         TIMESTAMPTZ,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      BIGINT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_conversation_participants_conv ON chat_conversation_participants (conversation_id);
CREATE INDEX idx_chat_conversation_participants_profile ON chat_conversation_participants (profile_id);

CREATE TABLE chat_conversation_blocks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               VARCHAR(36) NOT NULL,
    blocker_profile_id BIGINT      NOT NULL,
    blocked_profile_id BIGINT      NOT NULL,
    conversation_id    BIGINT,
    created_by         BIGINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by         BIGINT,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_conversation_blocks_blocker ON chat_conversation_blocks (blocker_profile_id);
CREATE INDEX idx_chat_conversation_blocks_blocked ON chat_conversation_blocks (blocked_profile_id);

CREATE TABLE chat_conversation_read_states (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    conversation_id      BIGINT      NOT NULL,
    profile_id           BIGINT      NOT NULL,
    last_read_message_id BIGINT,
    version              BIGINT      NOT NULL DEFAULT 0,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_conversation_read_states_conv ON chat_conversation_read_states (conversation_id);
CREATE INDEX idx_chat_conversation_read_states_profile ON chat_conversation_read_states (profile_id);

CREATE TABLE chat_messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              VARCHAR(36) NOT NULL,
    conversation_id   BIGINT      NOT NULL,
    sender_profile_id BIGINT      NOT NULL,
    type              VARCHAR(50) NOT NULL,
    content           TEXT,
    iv                TEXT,
    edited_at         TIMESTAMPTZ,
    deleted_at        TIMESTAMPTZ,
    created_by        BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by        BIGINT,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN chat_messages.iv IS
    'Base64-encoded AES-GCM initialization vector (12 bytes). Required to decrypt the message content.';

CREATE INDEX idx_chat_messages_conversation_id ON chat_messages (conversation_id);
CREATE INDEX idx_chat_messages_sender ON chat_messages (sender_profile_id);
CREATE INDEX idx_chat_messages_created_at ON chat_messages (conversation_id, created_at);

CREATE TABLE chat_message_keys (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          VARCHAR(36) NOT NULL,
    message_id    BIGINT      NOT NULL,
    profile_id    BIGINT      NOT NULL,
    encrypted_key TEXT        NOT NULL,
    created_by    BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by    BIGINT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE chat_message_keys IS
    'Per-recipient encrypted symmetric key for group messages. For direct messages this table is not used — the shared secret is derived via ECDH.';
COMMENT ON COLUMN chat_message_keys.encrypted_key IS
    'Base64-encoded AES message key, encrypted with the recipient''s ECDH public key.';

CREATE INDEX idx_chat_message_keys_message_id ON chat_message_keys (message_id);
CREATE INDEX idx_chat_message_keys_profile_id ON chat_message_keys (profile_id);

CREATE TABLE chat_message_medias (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    message_id BIGINT      NOT NULL,
    media_id   BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_message_medias_message_id ON chat_message_medias (message_id);

CREATE TABLE chat_message_reactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    message_id BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    reaction   VARCHAR(50) NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_message_reactions_message_id ON chat_message_reactions (message_id);

CREATE TABLE chat_message_reports (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                VARCHAR(36) NOT NULL,
    message_id          BIGINT      NOT NULL,
    reporter_profile_id BIGINT      NOT NULL,
    reason              TEXT,
    created_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          BIGINT,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_message_reports_message_id ON chat_message_reports (message_id);

CREATE TABLE chat_actor_inboxes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    profile_id           BIGINT      NOT NULL,
    conversation_id      BIGINT      NOT NULL,
    last_message_id      BIGINT,
    last_read_message_id BIGINT,
    unread_count         BIGINT      NOT NULL DEFAULT 0,
    pinned               BOOLEAN     NOT NULL DEFAULT FALSE,
    muted                BOOLEAN     NOT NULL DEFAULT FALSE,
    version              BIGINT      NOT NULL DEFAULT 0,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_actor_inboxes_profile_id ON chat_actor_inboxes (profile_id);
CREATE INDEX idx_chat_actor_inboxes_conversation_id ON chat_actor_inboxes (conversation_id);
--rollback DROP TABLE IF EXISTS chat_actor_inboxes; DROP TABLE IF EXISTS chat_message_reports; DROP TABLE IF EXISTS chat_message_reactions; DROP TABLE IF EXISTS chat_message_medias; DROP TABLE IF EXISTS chat_message_keys; DROP TABLE IF EXISTS chat_messages; DROP TABLE IF EXISTS chat_conversation_read_states; DROP TABLE IF EXISTS chat_conversation_blocks; DROP TABLE IF EXISTS chat_conversation_participants; DROP TABLE IF EXISTS chat_conversations;
