--liquibase formatted sql

--changeset ninggiangboy:005-01-create-chat-conversations
CREATE TABLE chat_conversations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                  VARCHAR(36) NOT NULL,
    type                  VARCHAR(50) NOT NULL,
    created_by_profile_id BIGINT      NOT NULL,
    last_message_id       BIGINT,
    last_message_at       TIMESTAMPTZ,
    created_by            BIGINT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by            BIGINT,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at            TIMESTAMPTZ
);

CREATE INDEX idx_chat_conversations_creator ON chat_conversations (created_by_profile_id);
CREATE INDEX idx_chat_conversations_last_message_at ON chat_conversations (last_message_at);
CREATE INDEX idx_chat_conversations_deleted_at ON chat_conversations (deleted_at);
--rollback DROP TABLE chat_conversations;

--changeset ninggiangboy:005-02-create-chat-conversation-participants
CREATE TABLE chat_conversation_participants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36) NOT NULL,
    conversation_id BIGINT      NOT NULL,
    profile_id      BIGINT      NOT NULL,
    role            VARCHAR(50) NOT NULL,
    joined_at       TIMESTAMPTZ,
    left_at         TIMESTAMPTZ,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by      BIGINT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_conversation_participants_conv ON chat_conversation_participants (conversation_id);
CREATE INDEX idx_chat_conversation_participants_profile ON chat_conversation_participants (profile_id);
--rollback DROP TABLE chat_conversation_participants;

--changeset ninggiangboy:005-03-create-chat-conversation-blocks
CREATE TABLE chat_conversation_blocks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               VARCHAR(36) NOT NULL,
    blocker_profile_id BIGINT      NOT NULL,
    blocked_profile_id BIGINT      NOT NULL,
    conversation_id    BIGINT,
    created_by         BIGINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by         BIGINT,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_conversation_blocks_blocker ON chat_conversation_blocks (blocker_profile_id);
CREATE INDEX idx_chat_conversation_blocks_blocked ON chat_conversation_blocks (blocked_profile_id);
--rollback DROP TABLE chat_conversation_blocks;

--changeset ninggiangboy:005-04-create-chat-conversation-read-states
CREATE TABLE chat_conversation_read_states (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                VARCHAR(36) NOT NULL,
    conversation_id     BIGINT      NOT NULL,
    profile_id          BIGINT      NOT NULL,
    last_read_message_id BIGINT,
    created_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          BIGINT,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_conversation_read_states_conv ON chat_conversation_read_states (conversation_id);
CREATE INDEX idx_chat_conversation_read_states_profile ON chat_conversation_read_states (profile_id);
--rollback DROP TABLE chat_conversation_read_states;

--changeset ninggiangboy:005-05-create-chat-messages
CREATE TABLE chat_messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid              VARCHAR(36) NOT NULL,
    conversation_id   BIGINT      NOT NULL,
    sender_profile_id BIGINT      NOT NULL,
    type              VARCHAR(50) NOT NULL,
    content           TEXT,
    edited_at         TIMESTAMPTZ,
    deleted_at        TIMESTAMPTZ,
    created_by        BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by        BIGINT,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_messages_conversation_id ON chat_messages (conversation_id);
CREATE INDEX idx_chat_messages_sender ON chat_messages (sender_profile_id);
CREATE INDEX idx_chat_messages_created_at ON chat_messages (conversation_id, created_at);
--rollback DROP TABLE chat_messages;

--changeset ninggiangboy:005-06-add-chat-conversations-last-message-fk
SELECT 1;
--rollback SELECT 1;

--changeset ninggiangboy:005-07-create-chat-message-medias
CREATE TABLE chat_message_medias (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    message_id BIGINT      NOT NULL,
    media_id   BIGINT      NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_message_medias_message_id ON chat_message_medias (message_id);
--rollback DROP TABLE chat_message_medias;

--changeset ninggiangboy:005-08-create-chat-message-reactions
CREATE TABLE chat_message_reactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    message_id BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    reaction   VARCHAR(50) NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_message_reactions_message_id ON chat_message_reactions (message_id);
--rollback DROP TABLE chat_message_reactions;

--changeset ninggiangboy:005-09-create-chat-message-reports
CREATE TABLE chat_message_reports (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                VARCHAR(36) NOT NULL,
    message_id          BIGINT      NOT NULL,
    reporter_profile_id BIGINT      NOT NULL,
    reason              TEXT,
    created_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          BIGINT,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_message_reports_message_id ON chat_message_reports (message_id);
--rollback DROP TABLE chat_message_reports;

--changeset ninggiangboy:005-10-create-chat-actor-inboxes
CREATE TABLE chat_actor_inboxes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                VARCHAR(36) NOT NULL,
    profile_id          BIGINT      NOT NULL,
    conversation_id     BIGINT      NOT NULL,
    last_message_id     BIGINT,
    last_read_message_id BIGINT,
    unread_count        BIGINT      NOT NULL DEFAULT 0,
    pinned              BOOLEAN     NOT NULL DEFAULT FALSE,
    muted               BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by          BIGINT,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_actor_inboxes_profile_id ON chat_actor_inboxes (profile_id);
CREATE INDEX idx_chat_actor_inboxes_conversation_id ON chat_actor_inboxes (conversation_id);
--rollback DROP TABLE chat_actor_inboxes;
