--liquibase formatted sql

--changeset ninggiangboy:007-01-create-group-tables
CREATE TABLE grp_groups (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid             VARCHAR(36)  NOT NULL,
    owner_profile_id BIGINT       NOT NULL,
    name             VARCHAR(100) NOT NULL,
    slug             VARCHAR(100) NOT NULL,
    description      TEXT,
    avatar_url       VARCHAR(500),
    banner_url       VARCHAR(500),
    visibility       VARCHAR(50)  NOT NULL DEFAULT 'PUBLIC',
    status           VARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',
    requires_approval BOOLEAN     NOT NULL DEFAULT FALSE,
    version          BIGINT       NOT NULL DEFAULT 0,
    created_by       BIGINT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by       BIGINT,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ
);

CREATE INDEX idx_grp_groups_owner_profile_id ON grp_groups (owner_profile_id);
CREATE INDEX idx_grp_groups_visibility ON grp_groups (visibility);
CREATE INDEX idx_grp_groups_status ON grp_groups (status);
CREATE INDEX idx_grp_groups_deleted_at ON grp_groups (deleted_at);

CREATE TABLE grp_group_stats (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         VARCHAR(36) NOT NULL,
    group_id     BIGINT      NOT NULL,
    member_count BIGINT      NOT NULL DEFAULT 0,
    thread_count BIGINT      NOT NULL DEFAULT 0,
    version      BIGINT      NOT NULL DEFAULT 0,
    created_by   BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by   BIGINT,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE grp_group_members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36) NOT NULL,
    group_id    BIGINT      NOT NULL,
    profile_id  BIGINT      NOT NULL,
    role        VARCHAR(50) NOT NULL,
    status      VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    muted_until TIMESTAMPTZ,
    permissions BIGINT      NOT NULL DEFAULT 0,
    version     BIGINT      NOT NULL DEFAULT 0,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN grp_group_members.permissions IS
    'Bitmask of GroupAdminPermission bits. Only meaningful for ADMIN role members. OWNER implicitly holds all permissions.';

CREATE INDEX idx_grp_group_members_group_id ON grp_group_members (group_id);
CREATE INDEX idx_grp_group_members_profile_id ON grp_group_members (profile_id);
CREATE INDEX idx_grp_group_members_role ON grp_group_members (role);
CREATE INDEX idx_grp_group_members_status ON grp_group_members (status);

CREATE TABLE grp_group_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        VARCHAR(36)  NOT NULL,
    group_id    BIGINT       NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    position    INTEGER      NOT NULL DEFAULT 0,
    created_by  BIGINT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by  BIGINT,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_grp_group_rules_group_id ON grp_group_rules (group_id);

CREATE TABLE grp_group_invitations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               VARCHAR(36)  NOT NULL,
    group_id           BIGINT       NOT NULL,
    inviter_profile_id BIGINT       NOT NULL,
    invitee_profile_id BIGINT       NOT NULL,
    status             VARCHAR(50)  NOT NULL DEFAULT 'PENDING',
    token              VARCHAR(255) NOT NULL,
    expires_at         TIMESTAMPTZ,
    version            BIGINT       NOT NULL DEFAULT 0,
    created_by         BIGINT,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_by         BIGINT,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_grp_group_invitations_group_id ON grp_group_invitations (group_id);
CREATE INDEX idx_grp_group_invitations_invitee_profile_id ON grp_group_invitations (invitee_profile_id);
CREATE INDEX idx_grp_group_invitations_status ON grp_group_invitations (status);

CREATE TABLE grp_group_member_requests (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                   VARCHAR(36) NOT NULL,
    group_id               BIGINT      NOT NULL,
    requester_profile_id   BIGINT      NOT NULL,
    status                 VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    reviewed_by_profile_id BIGINT,
    review_note            TEXT,
    version                BIGINT      NOT NULL DEFAULT 0,
    created_by             BIGINT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by             BIGINT,
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_grp_group_member_requests_group_id ON grp_group_member_requests (group_id);
CREATE INDEX idx_grp_group_member_requests_requester_profile_id ON grp_group_member_requests (requester_profile_id);
CREATE INDEX idx_grp_group_member_requests_status ON grp_group_member_requests (status);

CREATE TABLE grp_group_threads (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    group_id   BIGINT      NOT NULL,
    thread_id  BIGINT      NOT NULL,
    is_pinned  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_grp_group_threads_group_id ON grp_group_threads (group_id);
CREATE INDEX idx_grp_group_threads_thread_id ON grp_group_threads (thread_id);
CREATE INDEX idx_grp_group_threads_is_pinned ON grp_group_threads (is_pinned);

CREATE TABLE grp_group_moderation_actions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    group_id             BIGINT      NOT NULL,
    target_profile_id    BIGINT      NOT NULL,
    moderator_profile_id BIGINT      NOT NULL,
    action_type          VARCHAR(50) NOT NULL,
    reason               TEXT,
    expires_at           TIMESTAMPTZ,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_grp_group_moderation_actions_group_id ON grp_group_moderation_actions (group_id);
CREATE INDEX idx_grp_group_moderation_actions_target_profile_id ON grp_group_moderation_actions (target_profile_id);
CREATE INDEX idx_grp_group_moderation_actions_action_type ON grp_group_moderation_actions (action_type);
--rollback DROP TABLE IF EXISTS grp_group_moderation_actions; DROP TABLE IF EXISTS grp_group_threads; DROP TABLE IF EXISTS grp_group_member_requests; DROP TABLE IF EXISTS grp_group_invitations; DROP TABLE IF EXISTS grp_group_rules; DROP TABLE IF EXISTS grp_group_members; DROP TABLE IF EXISTS grp_group_stats; DROP TABLE IF EXISTS grp_groups;
