--liquibase formatted sql

--changeset ninggiangboy:008-01-create-attachment-tables
CREATE TABLE att_attachments (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                   VARCHAR(36)   NOT NULL,
    account_id             BIGINT        NOT NULL,
    type                   VARCHAR(255)  NOT NULL,
    object_key             VARCHAR(1024) NOT NULL,
    file_name              VARCHAR(500)  NOT NULL,
    content_type           VARCHAR(255)  NOT NULL,
    size_bytes             BIGINT,
    file_url               VARCHAR(2000),
    upload_status          VARCHAR(50)   NOT NULL DEFAULT 'PENDING_PUT',
    processed_at           TIMESTAMPTZ,
    processing_request_id  VARCHAR(120),
    processing_requested_at TIMESTAMPTZ,
    version                BIGINT        NOT NULL DEFAULT 0,
    created_by             BIGINT,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by             BIGINT,
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_att_attachments_uuid ON att_attachments (uuid);
CREATE INDEX idx_att_attachments_account_id ON att_attachments (account_id);
CREATE INDEX idx_att_attachments_object_key ON att_attachments (object_key);
CREATE INDEX idx_att_attachments_processed_at ON att_attachments (processed_at);
CREATE INDEX idx_att_attachments_upload_status_content_type ON att_attachments (upload_status, content_type);
CREATE INDEX idx_att_attachments_processing_requested_at ON att_attachments (processing_requested_at);
--rollback DROP TABLE IF EXISTS att_attachments;
