--liquibase formatted sql

--changeset ninggiangboy:009-01-add-e2e-encryption
ALTER TABLE prf_profiles
    ADD COLUMN public_key TEXT;

COMMENT ON COLUMN prf_profiles.public_key IS
    'Base64-encoded ECDH public key (X25519). Used for E2E encrypted message key exchange.';
--rollback ALTER TABLE prf_profiles DROP COLUMN public_key;

ALTER TABLE chat_messages
    ADD COLUMN iv TEXT;

COMMENT ON COLUMN chat_messages.iv IS
    'Base64-encoded AES-GCM initialization vector (12 bytes). Required to decrypt the message content.';
--rollback ALTER TABLE chat_messages DROP COLUMN iv;

CREATE TABLE chat_message_keys (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(36) NOT NULL,
    message_id BIGINT      NOT NULL,
    profile_id BIGINT      NOT NULL,
    encrypted_key TEXT     NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_chat_message_keys_message_id ON chat_message_keys (message_id);
CREATE INDEX idx_chat_message_keys_profile_id ON chat_message_keys (profile_id);

COMMENT ON TABLE chat_message_keys IS
    'Per-recipient encrypted symmetric key for group messages. For direct messages this table is not used — the shared secret is derived via ECDH.';
COMMENT ON COLUMN chat_message_keys.encrypted_key IS
    'Base64-encoded AES message key, encrypted with the recipient''s ECDH public key.';
--rollback DROP TABLE chat_message_keys;
