--liquibase formatted sql

--changeset ninggiangboy:010-01-create-att-attachments
CREATE TABLE att_attachments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid            VARCHAR(36)   NOT NULL,
    account_id      BIGINT        NOT NULL,
    bucket          VARCHAR(255)  NOT NULL,
    object_key      VARCHAR(1024) NOT NULL,
    file_name       VARCHAR(500)  NOT NULL,
    content_type    VARCHAR(255)  NOT NULL,
    size_bytes      BIGINT,
    file_url        VARCHAR(2000),
    upload_status   VARCHAR(50)   NOT NULL DEFAULT 'PENDING_PUT',
    created_by      BIGINT,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_by      BIGINT,
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_att_attachments_uuid ON att_attachments (uuid);
CREATE INDEX idx_att_attachments_account_id ON att_attachments (account_id);
CREATE INDEX idx_att_attachments_object_key ON att_attachments (object_key);
--rollback DROP TABLE att_attachments;
