--liquibase formatted sql

--changeset ninggiangboy:020-01-create-prf-follow-requests
CREATE TABLE prf_follow_requests (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                 VARCHAR(36) NOT NULL,
    requester_profile_id BIGINT      NOT NULL,
    target_profile_id    BIGINT      NOT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    responded_at         TIMESTAMPTZ,
    created_by           BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by           BIGINT,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE prf_follow_requests IS
    'Pending follow requests created when a user attempts to follow a PRIVATE profile.';
COMMENT ON COLUMN prf_follow_requests.status IS
    'Lifecycle: PENDING, APPROVED, REJECTED, CANCELLED.';

CREATE UNIQUE INDEX uq_prf_follow_requests_pending_pair
    ON prf_follow_requests (requester_profile_id, target_profile_id)
    WHERE status = 'PENDING';

CREATE INDEX idx_prf_follow_requests_target_status
    ON prf_follow_requests (target_profile_id, status);

CREATE INDEX idx_prf_follow_requests_requester_status
    ON prf_follow_requests (requester_profile_id, status);
--rollback DROP TABLE prf_follow_requests;
