plugins {
    id 'org.springframework.boot'
}

dependencies {
    testImplementation 'io.vavr:vavr:0.10.6'

    implementation project(':core:domain')
    implementation project(':core:database')

    implementation project(':libs:common')
    implementation project(':libs:infrastructure')
    implementation project(':libs:utils')
    implementation project(':libs:constant')
}