plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation 'com.graphql-java:graphql-java-extended-scalars:24.0'

    testImplementation 'io.vavr:vavr:0.10.6'
    testImplementation 'org.springframework.modulith:spring-modulith-starter-test'

    implementation project(':core:domain')
    implementation project(':core:database')

    implementation project(':libs:common')
    implementation project(':libs:infrastructure')
    implementation project(':libs:utils')
    implementation project(':libs:constant')
}