plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':core:domain')
    implementation project(':core:database')

    implementation project(':libs:common')
    implementation project(':libs:infrastructure')
    implementation project(':libs:utils')
    implementation project(':libs:constant')

    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
}